spring:
  application:
    name: GATEWAY-SERVICE

  cloud:
    gateway:
      routes:
        - id: processcomponent-service
          uri: lb://PROCESSCOMPONENT-SERVICE
          predicates:
            - Path=/processcomponent/**
        - id: packaginganddelivery-service
          uri: lb://PACKAGINGANDDELIVERY-SERVICE
          predicates:
            - Path=/packaginganddelivery/**
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost
    
    
server:
  port: 8989